name: Portfolio Website CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ dev ]

jobs:
  ci:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Linter
        uses: super-linter/super-linter@v7
        env:
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}